// Error Code Enums - Use these codes for API error responses
// Frontend should handle these codes to display appropriate user messages

const ErrorCode = {
  // Authentication & Authorization Errors (1xxx)
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_BANNED: 'AUTH_ACCOUNT_BANNED',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',
  AUTH_NO_TOKEN_PROVIDED: 'AUTH_NO_TOKEN_PROVIDED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_EMAIL_NOT_PROVIDED: 'AUTH_EMAIL_NOT_PROVIDED',

  // Registration Errors (2xxx)
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  USERNAME_ALREADY_TAKEN: 'USERNAME_ALREADY_TAKEN',

  // Platform Integration Errors (3xxx)
  // Steam
  STEAM_LIBRARY_FAILED: 'STEAM_LIBRARY_FAILED',

  // Xbox
  XBOX_GAMERTAG_NOT_FOUND: 'XBOX_GAMERTAG_NOT_FOUND',
  XBOX_PROFILE_FAILED: 'XBOX_PROFILE_FAILED',
  XBOX_LIBRARY_FAILED: 'XBOX_LIBRARY_FAILED',
  XBOX_XUID_NOT_FOUND: 'XBOX_XUID_NOT_FOUND',

  // PSN
  PSN_INVALID_NPSSO: 'PSN_INVALID_NPSSO',
  PSN_LIBRARY_FAILED: 'PSN_LIBRARY_FAILED',

  // Nintendo
  NINTENDO_NOT_IMPLEMENTED: 'NINTENDO_NOT_IMPLEMENTED',

  // Epic
  EPIC_NOT_IMPLEMENTED: 'EPIC_NOT_IMPLEMENTED',

  // Generic Platform
  PLATFORM_NOT_IMPLEMENTED: 'PLATFORM_NOT_IMPLEMENTED',
  PLATFORM_UNKNOWN: 'PLATFORM_UNKNOWN',
  PLATFORM_NOT_CONNECTED: 'PLATFORM_NOT_CONNECTED',

  // IGDB Errors (4xxx)
  IGDB_AUTH_FAILED: 'IGDB_AUTH_FAILED',

  // Library & Game Errors (5xxx)
  GAME_NOT_FOUND: 'GAME_NOT_FOUND',
  GAME_ALREADY_IN_LIBRARY: 'GAME_ALREADY_IN_LIBRARY',
  GAME_NOT_IN_LIBRARY: 'GAME_NOT_IN_LIBRARY',
  MAPPING_NOT_FOUND: 'MAPPING_NOT_FOUND',

  // Social & Follow Errors (6xxx)
  CANNOT_FOLLOW_YOURSELF: 'CANNOT_FOLLOW_YOURSELF',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ALREADY_FOLLOWING: 'ALREADY_FOLLOWING',
  NOT_FOLLOWING: 'NOT_FOLLOWING',

  // Review Errors (6.5xxx)
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
  REVIEW_NOT_AUTHORIZED: 'REVIEW_NOT_AUTHORIZED',
  REVIEW_ALREADY_LIKED: 'REVIEW_ALREADY_LIKED',
  REVIEW_LIKE_NOT_FOUND: 'REVIEW_LIKE_NOT_FOUND',

  // Reply Errors (6.6xxx)
  REPLY_NOT_FOUND: 'REPLY_NOT_FOUND',
  REPLY_NOT_AUTHORIZED: 'REPLY_NOT_AUTHORIZED',

  // Report Errors (6.7xxx)
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  ALREADY_REPORTED: 'ALREADY_REPORTED',

  // Validation Errors (7xxx)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Upload Errors (7.5xxx)
  NO_FILE_UPLOADED: 'NO_FILE_UPLOADED',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',

  // Database Errors (8xxx)
  DB_UNIQUE_CONSTRAINT: 'DB_UNIQUE_CONSTRAINT',
  DB_RECORD_NOT_FOUND: 'DB_RECORD_NOT_FOUND',
  DB_FOREIGN_KEY_CONSTRAINT: 'DB_FOREIGN_KEY_CONSTRAINT',

  // Generic Errors (9xxx)
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  ENDPOINT_NOT_FOUND: 'ENDPOINT_NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
};

module.exports = {
  ErrorCode,
};
